Sorting dacs
Giveth/giveth-dapp pull request #1503
Opened 2020-11-03 02:11 UTC by arbreton

https://github.com/Giveth/giveth-dapp/issues/1464

2020-11-04 09:50 UTC, aminlatifi requested changes

2020-11-04 09:50 UTC, aminlatifi commented on src/services/DACService.js
> +          $sort: { updatedAt: -1 },
It shouldn't be changed

2020-11-04 09:50 UTC, aminlatifi commented on src/services/CampaignService.js
> +            $lt: new Date(),
What's the purpose of this line? it should be deleted.

2020-11-04 09:50 UTC, aminlatifi commented on src/services/DACService.js
> +            $lt: new Date(),
This should be removed too!

2020-11-12 17:37 UTC, arbreton commented
updated PR @aminlatifi

2020-11-21 15:50 UTC, aminlatifi approved these changes

2020-11-21 15:51 UTC, aminlatifi commented
It's not working, for example this milestone is update in 2018
https://beta.giveth.io/campaigns/5b37e9daa239ac21b383d4e0

But still is shown after this change

2020-11-23 19:49 UTC, aminlatifi requested changes
Doesn't work as expected

2020-12-03 19:11 UTC, papermache commented
Still testing.

2020-12-14 16:14 UTC, GriffGreen commented
still needs changes

2021-01-01 20:27 UTC, aminlatifi commented
> It's not working, for example this milestone is update in 2018
> https://beta.giveth.io/campaigns/5b37e9daa239ac21b383d4e0
> 
> But still is shown after this change

Sorry, it was my mistake, it was working. We have implemented this and put the limit in config in another PR.

2021-01-01 20:27 UTC, closed without merging