gh-1414 min amount for delegating to DACs
Giveth/giveth-dapp pull request #1539
Opened 2020-11-23 18:51 UTC by arbreton

2020-11-23 19:57 UTC, aminlatifi requested changes
The implementation doesn't address issue #1414 requirement. You should obtain the usd value of original donation and compare it with 40$. If it's less than that ignore donating to DAC

2020-11-23 19:57 UTC, aminlatifi commented on src/components/DonateButton.jsx
> +      const amountDAC = parseFloat(maxDonationAmount - maxDonationAmount / 1.03)
If you want to get the amount will be donated to dac, can simply write `maxDonationAmount * 0.03`

2020-12-07 16:38 UTC, arbreton commented
Will check on the USD value

2020-12-07 22:19 UTC, aminlatifi commented
We are implementing an api on feathers for hourly rates, you can use it after is merged
https://github.com/Giveth/feathers-giveth/pull/287

2020-12-14 09:15 UTC, arbreton commented
Sounds great, will do

2021-01-31 20:37 UTC, closed without merging