F 1486 Auto updating new donations for milestone, campaign and DAC views
Giveth/giveth-dapp pull request #1951
Opened 2021-03-22 22:27 UTC by RamRamez

Issue #1486

2021-03-25 09:48 UTC, aminlatifi requested changes
@RamRamez Campaign related pages are reviewed, it should be changed in a way to fix issues we discussed. Please fix other views too (DAC and Milestone)

2021-03-25 09:48 UTC, aminlatifi commented on src/components/views/ViewCampaign.jsx
> +          const allDonations = [..._donations, ...donations];
It contacts the same donations multiple time and creates huge list

2021-03-25 09:48 UTC, aminlatifi commented on src/components/views/ViewCampaign.jsx
> +                  new Date(lastCommittedDonation.current._createdAt) < new Date(item._createdAt)
It's not necessary since we have newDonations from subscription

2021-03-25 09:48 UTC, aminlatifi commented on src/components/views/ViewCampaign.jsx
> +                  updateLeaderboard();
updateLeaderBoard should be called just once new committed/waiting donation is created

2021-03-25 09:48 UTC, aminlatifi commented on src/components/views/ViewCampaign.jsx
> +            allDonations.forEach(item => {
Probably allDonations will be removed and is useless on new logic we discussed. By the way using Array.some is better approach

2021-03-25 09:48 UTC, aminlatifi commented on src/components/views/ViewMilestone.jsx
> +        donationsObserver = MilestoneService.subscribeNewDonations(
We may need to subscription types for milestone, one for any non failed donations and one for not failed and not pending maybe

2021-04-20 19:30 UTC, RamRamez commented
This PR will be continued on PR #2055

2021-04-20 19:30 UTC, closed without merging