F 2045 2123 2124 new designed milestone forms for editing
Giveth/giveth-dapp pull request #2126
Opened 2021-05-05 16:03 UTC by RamRamez

1. new designed milestone forms for editing
2. wrong notification after milestone update
3. Add formType field to milestone creation form and Milestone object

2021-05-06 08:52 UTC, aminlatifi requested changes
Combining create/propose and editing forms makes views complex and hard to debug. @RamRamez Please create separate view for editing each milestone form type, like EditBounty, EditExpenses, etc.

2021-05-06 08:52 UTC, aminlatifi commented on src/components/EditMilestoneButton.jsx
> +        if (formType) {
Limit form type possible values

2021-05-06 08:52 UTC, aminlatifi commented on src/containers/Routes.jsx
> +            balance={balance}
These three fields can be removed

2021-05-06 08:52 UTC, aminlatifi commented on src/containers/Routes.jsx
> +            balance={balance}
Also from next two tags

2021-05-06 08:52 UTC, aminlatifi commented on src/components/views/CreateBounty.jsx
> +              res.donationCounters.length > 0
This condition is wrong, a milestone having some donations can be edited by a user who is not milestone owner neither campaign owner

2021-05-06 08:52 UTC, aminlatifi commented on src/components/views/CreateBounty.jsx
> +    if (!isNew && currentUser.id) {
What if user doesn't have any `id`? a user which has not signed in or created profile

2021-05-06 08:52 UTC, aminlatifi commented on src/components/views/CreateBounty.jsx
> +            getCampaign(res.campaign.slug).then();
Why get campaign again? milestone entity already has it

2021-05-11 18:29 UTC, aminlatifi commented
> It's not possible to edit title of an already accepted expense trance
> Happened on develop `/expense/609a9c9de66558424a7f9a28/edit`
> ![image](https://user-images.githubusercontent.com/5684607/117865706-7d85bb00-b2ab-11eb-8746-27cccefb4bd8.png)

@RamRamez Please test it for other fields.

2021-05-12 17:42 UTC, aminlatifi commented
@RamRamez There is an issue on setting conversion rates
```
index.js:1 save milestone error 
BadRequest {type: "FeathersError", name: "BadRequest", message: "Validation failed: items.0.conversionRateTimestamp…tedFiatType: Path `selectedFiatType` is required.", code: 400, className: "bad-request", …}
className: "bad-request"
code: 400
data: undefined
errors: {items.0.conversionRateTimestamp: {…}, items.0.conversionRate: {…}, items.0.wei: {…}, items.0.fiatAmount: {…}, items.0.selectedFiatType: {…}, …}
hook: {type: "before", arguments: Array(2), service: {…}, app: {…}, method: "patch", …}
message: "Validation failed: items.0.conversionRateTimestamp: Path `conversionRateTimestamp` is required., items.0.conversionRate: Path `conversionRate` is required., items.0.wei: Path `wei` is required., items.0.fiatAmount: Path `fiatAmount` is required., items.0.selectedFiatType: Path `selectedFiatType` is required., items.1.conversionRateTimestamp: Path `conversionRateTimestamp` is required., items.1.conversionRate: Path `conversionRate` is required., items.1.wei: Path `wei` is required., items.1.fiatAmount: Path `fiatAmount` is required., items.1.selectedFiatType: Path `selectedFiatType` is required."
name: "BadRequest"
type: "FeathersError"
stack: "BadRequest: Validation failed: items.0.conversionRateTimestamp: Path `conversionRateTimestamp` is required., items.0.conversionRate: Path `conversionRate` is required., items.0.wei: Path `wei` is required., items.0.fiatAmount: Path `fiatAmount` is required., items.0.selectedFiatType: Path `selectedFiatType` is required., items.1.conversionRateTimestamp: Path `conversionRateTimestamp` is required., items.1.conversionRate: Path `conversionRate` is required., items.1.wei: Path `wei` is required., items.1.fiatAmount: Path `fiatAmount` is required., items.1.selectedFiatType: Path `selectedFiatType` is required.\n    at new BadRequest (http://localhost:3010/static/js/vendors~main.chunk.js:178438:17)\n    at convert (http://localhost:3010/static/js/vendors~main.chunk.js:178574:32)\n    at Socket.<anonymous> (http://localhost:3010/static/js/vendors~main.chunk.js:182484:47)\n    at Socket.push../node_modules/socket.io-client/lib/socket.js.Socket.onack (http://localhost:3010/static/js/vendors~main.chunk.js:393322:9)\n    at Socket.push../node_modules/socket.io-client/lib/socket.js.Socket.onpacket (http://localhost:3010/static/js/vendors~main.chunk.js:393247:12)\n    at Manager.<anonymous> (http://localhost:3010/static/js/vendors~main.chunk.js:148671:15)\n    at Manager.push../node_modules/component-emitter/index.js.Emitter.emit (http://localhost:3010/static/js/vendors~main.chunk.js:148823:20)\n    at Manager.push../node_modules/socket.io-client/lib/manager.js.Manager.ondecoded (http://localhost:3010/static/js/vendors~main.chunk.js:392741:8)\n    at Decoder.<anonymous> (http://localhost:3010/static/js/vendors~main.chunk.js:148671:15)\n    at Decoder.push../node_modules/component-emitter/index.js.Emitter.emit (http://localhost:3010/static/js/vendors~main.chunk.js:148823:20)\n    at Decoder.push../node_modules/socket.io-parser/index.js.Decoder.add (http://localhost:3010/static/js/vendors~main.chunk.js:394508:12)\n    at Manager.push../node_modules/socket.io-client/lib/manager.js.Manager.ondata (http://localhost:3010/static/js/vendors~main.chunk.js:392731:16)\n    at Socket.<anonymous> (http://localhost:3010/static/js/vendors~main.chunk.js:148671:15)\n    at Socket.push../node_modules/component-emitter/index.js.Emitter.emit (http://localhost:3010/static/js/vendors~main.chunk.js:148823:20)\n    at Socket.push../node_modules/engine.io-client/lib/socket.js.Socket.onPacket (http://localhost:3010/static/js/vendors~main.chunk.js:166181:14)\n    at WS.<anonymous> (http://localhost:3010/static/js/vendors~main.chunk.js:166007:10)\n    at WS.push../node_modules/component-emitter/index.js.Emitter.emit (http://localhost:3010/static/js/vendors~main.chunk.js:148823:20)\n    at WS.push../node_modules/engine.io-client/lib/transport.js.Transport.onPacket (http://localhost:3010/static/js/vendors~main.chunk.js:166610:8)\n    at WS.push../node_modules/engine.io-client/lib/transport.js.Transport.onData (http://localhost:3010/static/js/vendors~main.chunk.js:166602:8)\n    at WebSocket.ws.onmessage (http://localhost:3010/static/js/vendors~main.chunk.js:167781:10)"
__proto__: Error
```

2021-05-12 23:19 UTC, RamRamez commented
> @RamRamez There is an issue on setting conversion rates
> 
> ```
> index.js:1 save milestone error 
> BadRequest {type: "FeathersError", name: "BadRequest", message: "Validation failed: items.0.conversionRateTimestamp…tedFiatType: Path `selectedFiatType` is required.", code: 400, className: "bad-request", …}
> className: "bad-request"
> code: 400
> data: undefined
> errors: {items.0.conversionRateTimestamp: {…}, items.0.conversionRate: {…}, items.0.wei: {…}, items.0.fiatAmount: {…}, items.0.selectedFiatType: {…}, …}
> hook: {type: "before", arguments: Array(2), service: {…}, app: {…}, method: "patch", …}
> message: "Validation failed: items.0.conversionRateTimestamp: Path `conversionRateTimestamp` is required., items.0.conversionRate: Path `conversionRate` is required., items.0.wei: Path `wei` is required., items.0.fiatAmount: Path `fiatAmount` is required., items.0.selectedFiatType: Path `selectedFiatType` is required., items.1.conversionRateTimestamp: Path `conversionRateTimestamp` is required., items.1.conversionRate: Path `conversionRate` is required., items.1.wei: Path `wei` is required., items.1.fiatAmount: Path `fiatAmount` is required., items.1.selectedFiatType: Path `selectedFiatType` is required."
> name: "BadRequest"
> type: "FeathersError"
> stack: "BadRequest: Validation failed: items.0.conversionRateTimestamp: Path `conversionRateTimestamp` is required., items.0.conversionRate: Path `conversionRate` is required., items.0.wei: Path `wei` is required., items.0.fiatAmount: Path `fiatAmount` is required., items.0.selectedFiatType: Path `selectedFiatType` is required., items.1.conversionRateTimestamp: Path `conversionRateTimestamp` is required., items.1.conversionRate: Path `conversionRate` is required., items.1.wei: Path `wei` is required., items.1.fiatAmount: Path `fiatAmount` is required., items.1.selectedFiatType: Path `selectedFiatType` is required.\n    at new BadRequest (http://localhost:3010/static/js/vendors~main.chunk.js:178438:17)\n    at convert (http://localhost:3010/static/js/vendors~main.chunk.js:178574:32)\n    at Socket.<anonymous> (http://localhost:3010/static/js/vendors~main.chunk.js:182484:47)\n    at Socket.push../node_modules/socket.io-client/lib/socket.js.Socket.onack (http://localhost:3010/static/js/vendors~main.chunk.js:393322:9)\n    at Socket.push../node_modules/socket.io-client/lib/socket.js.Socket.onpacket (http://localhost:3010/static/js/vendors~main.chunk.js:393247:12)\n    at Manager.<anonymous> (http://localhost:3010/static/js/vendors~main.chunk.js:148671:15)\n    at Manager.push../node_modules/component-emitter/index.js.Emitter.emit (http://localhost:3010/static/js/vendors~main.chunk.js:148823:20)\n    at Manager.push../node_modules/socket.io-client/lib/manager.js.Manager.ondecoded (http://localhost:3010/static/js/vendors~main.chunk.js:392741:8)\n    at Decoder.<anonymous> (http://localhost:3010/static/js/vendors~main.chunk.js:148671:15)\n    at Decoder.push../node_modules/component-emitter/index.js.Emitter.emit (http://localhost:3010/static/js/vendors~main.chunk.js:148823:20)\n    at Decoder.push../node_modules/socket.io-parser/index.js.Decoder.add (http://localhost:3010/static/js/vendors~main.chunk.js:394508:12)\n    at Manager.push../node_modules/socket.io-client/lib/manager.js.Manager.ondata (http://localhost:3010/static/js/vendors~main.chunk.js:392731:16)\n    at Socket.<anonymous> (http://localhost:3010/static/js/vendors~main.chunk.js:148671:15)\n    at Socket.push../node_modules/component-emitter/index.js.Emitter.emit (http://localhost:3010/static/js/vendors~main.chunk.js:148823:20)\n    at Socket.push../node_modules/engine.io-client/lib/socket.js.Socket.onPacket (http://localhost:3010/static/js/vendors~main.chunk.js:166181:14)\n    at WS.<anonymous> (http://localhost:3010/static/js/vendors~main.chunk.js:166007:10)\n    at WS.push../node_modules/component-emitter/index.js.Emitter.emit (http://localhost:3010/static/js/vendors~main.chunk.js:148823:20)\n    at WS.push../node_modules/engine.io-client/lib/transport.js.Transport.onPacket (http://localhost:3010/static/js/vendors~main.chunk.js:166610:8)\n    at WS.push../node_modules/engine.io-client/lib/transport.js.Transport.onData (http://localhost:3010/static/js/vendors~main.chunk.js:166602:8)\n    at WebSocket.ws.onmessage (http://localhost:3010/static/js/vendors~main.chunk.js:167781:10)"
> __proto__: Error
> ```

Thanks, t's fixed.

2021-05-15 22:10 UTC, aminlatifi reviewed
I created a Payment trace (milestone) with capacity. Then I edited it and made it uncapped (check no limit). It didn't work.

2021-05-15 22:14 UTC, aminlatifi requested changes
Thank you @RamRamez . Please resolve mentioned comments and let's go for test 😃

2021-05-15 22:14 UTC, aminlatifi commented on src/components/views/EditMilestone.jsx
> +      setMilestone(ms);
This probably has no effect

2021-05-15 22:14 UTC, aminlatifi commented on src/components/views/EditPayment.jsx
> +      if (!notCapped) {
We should have an else statement for this condition and clear max amount and other fields if milestone is not capped.

@RamRamez refer to this
https://github.com/Giveth/giveth-dapp/pull/2126#pullrequestreview-660389475

2021-05-16 13:20 UTC, aminlatifi commented
Thanks @RamRamez

2021-05-16 13:20 UTC, merged