2264 update win10 installation instructions in README.md
Giveth/giveth-dapp pull request #2266
Opened 2021-06-09 20:29 UTC by hytung8

Closes #2264

Checklist:
 I have read Giveth's contribution guidelines.
 My pull request has a descriptive title.
 I have viewed these changes either locally on my machine or on github.

Details:
README.md:  I updated the Windows10 installation procedure based on steps suggested by Ramin.  I added links to Discord (in addition to Element) and that Node v10.24.1 should be used (removing references to Node v8).  I also suggested installing git (for those that installed github desktop).  I uploaded a screenshot VSstudio.png which is referenced in the README.md Windows10 install procedure.

2021-06-10 06:29 UTC, aminlatifi commented
@hytung8 Thanks a lot.

2021-06-13 12:20 UTC, RamRamez requested changes
Thanks @hytung8

2021-06-13 12:20 UTC, RamRamez commented on README.md
> +REACT_APP_DAC_FACTORY_ADDRESS | Differs per REACT_APP_ENVIRONMENT | Overwrites the DACs contract address. |
We've changed the "DACs" word to "Communities" and "Milestones" word to "Traces".
Please update your version with the latest README file.

2021-06-13 12:20 UTC, RamRamez commented on README.md
> +- editing of DACs/Campaigns/Milestones
Also here

2021-06-28 08:29 UTC, RamRamez commented
It's done in PR #2297

2021-06-28 08:29 UTC, closed without merging